const API_BASE = '/api/journal';
const AUTH_BASE = '/api/auth';

const journalPrompts = [
    // Original prompts
    "What changed in your energy after today's release?",
    "What truth is ready to emerge?",
    "Where does this feeling live in your body?",
    "What would you say to your younger self about this emotion?",
    "What permission are you giving yourself today?",
    "What are you ready to let go of?",
    "How does freedom feel in this moment?",
    "What wisdom is your body sharing with you?",
    
    // Emotional Integration & Awareness
    "What emotion surprised you the most today?",
    "If this emotion had a message, what would it say?",
    "What old pattern are you beginning to see more clearly?",
    "What emotion do you often avoid, and why?",
    "What needs your forgiveness today?",
    
    // Body & Energy Connection
    "What part of your body feels lighter after this release?",
    "If your heart could speak, what would it whisper?",
    "How does your breath feel now compared to before?",
    "What color do you feel in your body after this session?",
    "Is there tension anywhere that still needs your attention?",
    
    // Inner Child & Compassion Work
    "What would your inner child like you to know today?",
    "How can you offer more kindness to yourself in this moment?",
    "What belief are you willing to reframe with love?",
    "What would it look like to accept yourself fully, right now?",
    
    // Letting Go & Becoming
    "What are you still carrying that no longer belongs to you?",
    "Who are you becoming as you release this layer?",
    "What does your next version of wholeness feel like?",
    "What old story are you rewriting today?",
    "How do you wish to show up moving forward?",
    
    // Sacred Self & Higher Guidance
    "What did your higher self reveal during today's process?",
    "What synchronicities have been guiding you lately?",
    "What does your soul need from you this week?",
    "What truth are you ready to speak aloud?",
    "How does divine support feel when you tune in?"
];

const emotions = ['Fear', 'Guilt', 'Shame', 'Grief', 'Anger', 'Despair', 'Abandonment', 'Rejection', 'Hopelessness', 'Powerlessness', 'Anxiety', 'Worthlessness'];

const frequencyTags = ['Be Courage', 'Be Peace', 'Be Love', 'Be Joy', 'Be Gratitude', 'Be Empowered', 'Be Free', 'Be Whole'];

const vibrationWords = ['Radiant', 'Grounded', 'Flowing', 'Luminous', 'Peaceful', 'Vibrant', 'Clear', 'Harmonious'];

let currentPrompt = null;
let currentUser = null;
let lastAutoGeneratedEmotions = ''; // Track auto-generated emotion text

// Emotion dropdown management
function toggleEmotionDropdown() {
    const trigger = document.getElementById('emotion-dropdown-trigger');
    const dropdown = document.getElementById('emotion-dropdown');
    const isOpen = dropdown.classList.contains('open');
    
    if (isOpen) {
        closeEmotionDropdown();
    } else {
        openEmotionDropdown();
    }
}

function openEmotionDropdown() {
    const trigger = document.getElementById('emotion-dropdown-trigger');
    const dropdown = document.getElementById('emotion-dropdown');
    
    dropdown.classList.add('open');
    trigger.classList.add('active');
    trigger.setAttribute('aria-expanded', 'true');
}

function closeEmotionDropdown() {
    const trigger = document.getElementById('emotion-dropdown-trigger');
    const dropdown = document.getElementById('emotion-dropdown');
    
    dropdown.classList.remove('open');
    trigger.classList.remove('active');
    trigger.setAttribute('aria-expanded', 'false');
}

function updateEmotionSelection() {
    const checkboxes = document.querySelectorAll('#emotion-dropdown input[type="checkbox"]');
    const selected = Array.from(checkboxes)
        .filter(cb => cb.checked)
        .map(cb => cb.value);
    
    // Update trigger text
    const triggerText = document.getElementById('emotion-dropdown-text');
    if (selected.length === 0) {
        triggerText.textContent = 'Select emotions...';
    } else if (selected.length === 1) {
        triggerText.textContent = selected[0];
    } else {
        triggerText.textContent = `${selected.length} emotions selected`;
    }
    
    // Update hidden input for form submission
    const hiddenInput = document.getElementById('emotion_selected');
    hiddenInput.value = selected.join(', ');
    
    // Auto-populate the "Emotions Released" textarea
    const emotionsReleasedTextarea = document.getElementById('emotions_released');
    if (emotionsReleasedTextarea) {
        const currentValue = emotionsReleasedTextarea.value.trim();
        // Update if: empty, OR matches last auto-generated value (user hasn't customized)
        if (currentValue === '' || currentValue === lastAutoGeneratedEmotions) {
            const newValue = selected.join(', ');
            emotionsReleasedTextarea.value = newValue;
            lastAutoGeneratedEmotions = newValue;
        }
    }
}

function clearEmotionSelection() {
    const checkboxes = document.querySelectorAll('#emotion-dropdown input[type="checkbox"]');
    checkboxes.forEach(cb => cb.checked = false);
    lastAutoGeneratedEmotions = ''; // Reset tracking
    updateEmotionSelection();
    // Also clear the emotions released textarea
    const emotionsReleasedTextarea = document.getElementById('emotions_released');
    if (emotionsReleasedTextarea) {
        emotionsReleasedTextarea.value = '';
    }
}

// Close dropdown when clicking outside
document.addEventListener('click', function(event) {
    const multiSelect = document.querySelector('.custom-multi-select');
    if (multiSelect && !multiSelect.contains(event.target)) {
        closeEmotionDropdown();
    }
});

// Close dropdown with ESC key
document.addEventListener('keydown', function(event) {
    if (event.key === 'Escape') {
        closeEmotionDropdown();
    }
});

function displayAffirmation() {
    const select = document.getElementById('affirmation-select');
    const selectedValue = select.value;
    const displayElement = document.getElementById('selected-affirmation');
    const affirmationInput = document.getElementById('affirmation');
    
    if (selectedValue) {
        displayElement.textContent = selectedValue;
        displayElement.style.display = 'block';
        affirmationInput.value = selectedValue;
    } else {
        displayElement.textContent = '';
        displayElement.style.display = 'none';
        affirmationInput.value = '';
    }
}

// Check if in quiet mode (free access, login only for saving)
function isQuietMode() {
    const params = new URLSearchParams(window.location.search);
    return params.get('mode') === 'quiet';
}

async function checkAuthentication() {
    try {
        const response = await fetch(`${AUTH_BASE}/check`);
        const data = await response.json();
        
        if (!data.authenticated) {
            // In quiet mode, allow access without login
            if (isQuietMode()) {
                currentUser = null;
                return false;
            }
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
            return false;
        }
        
        currentUser = data.user;
        return true;
    } catch (error) {
        console.error('Error checking authentication:', error);
        // In quiet mode, allow access even on error
        if (isQuietMode()) {
            currentUser = null;
            return false;
        }
        window.location.href = '/login.html';
        return false;
    }
}

function getRandomPrompt() {
    return journalPrompts[Math.floor(Math.random() * journalPrompts.length)];
}

function showNewPrompt() {
    currentPrompt = getRandomPrompt();
    document.getElementById('current-prompt').textContent = currentPrompt;
    document.getElementById('prompt-display').style.display = 'block';
    document.getElementById('prompt-used-hidden').value = currentPrompt;
}

function skipPrompt() {
    currentPrompt = null;
    document.getElementById('prompt-display').style.display = 'none';
    document.getElementById('prompt-used-hidden').value = '';
    document.getElementById('prompt-selector').value = '';
}

function selectPromptFromDropdown() {
    const selector = document.getElementById('prompt-selector');
    const selectedPrompt = selector.value;
    
    if (selectedPrompt) {
        currentPrompt = selectedPrompt;
        document.getElementById('current-prompt').textContent = currentPrompt;
        document.getElementById('prompt-display').style.display = 'block';
        document.getElementById('prompt-used-hidden').value = currentPrompt;
    }
}

function populatePromptDropdown() {
    const selector = document.getElementById('prompt-selector');
    
    journalPrompts.forEach((prompt, index) => {
        const option = document.createElement('option');
        option.value = prompt;
        option.textContent = prompt;
        selector.appendChild(option);
    });
}

async function loadEntries() {
    try {
        const response = await fetch(`${API_BASE}/entries`);
        
        if (response.status === 401) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
            return;
        }
        
        const entries = await response.json();
        displayEntries(entries);
    } catch (error) {
        console.error('Error loading entries:', error);
        if (error.message.includes('401')) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
        }
    }
}

function formatDate(isoString) {
    const date = new Date(isoString);
    return date.toLocaleString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
}

function displayEntries(entries) {
    const container = document.getElementById('journal-entries');
    
    if (entries.length === 0) {
        container.innerHTML = '<p class="no-entries">No journal entries yet. Start your healing journey above.</p>';
        return;
    }
    
    container.innerHTML = entries.map(entry => `
        <div class="journal-entry">
            <div class="entry-header">
                <span class="entry-date">${formatDate(entry.created_at)}</span>
                <div class="entry-actions">
                    <button onclick="downloadPDF(${entry.id})" class="pdf-btn">Download</button>
                    <button onclick="uploadToDrive(${entry.id})" class="drive-btn">Save to Drive</button>
                    <button onclick="deleteEntry(${entry.id})" class="delete-btn">Delete</button>
                </div>
            </div>
            
            <div class="entry-affirmation">
                <h3>🌟 Affirmation</h3>
                <p>${entry.affirmation}</p>
            </div>
            
            ${entry.emotion_selected || entry.frequency_tag || entry.vibration_word ? `
            <div class="entry-tags">
                ${entry.emotion_selected ? `<span class="entry-tag emotion-tag">${entry.emotion_selected}</span>` : ''}
                ${entry.frequency_tag ? `<span class="entry-tag frequency-tag">${entry.frequency_tag}</span>` : ''}
                ${entry.vibration_word ? `<span class="entry-tag vibration-tag">${entry.vibration_word}</span>` : ''}
            </div>
            ` : ''}
            
            ${entry.prompt_used ? `
            <div class="entry-prompt">
                <h4>💭 Prompt</h4>
                <p><em>"${entry.prompt_used}"</em></p>
            </div>
            ` : ''}
            
            <div class="entry-content">
                ${entry.general_reflection ? `
                <div class="entry-field general-reflection-field">
                    <h4>💫 Daily Reflection & Insights</h4>
                    <p>${entry.general_reflection}</p>
                </div>
                ` : ''}
                
                ${entry.feelings ? `
                <div class="entry-field">
                    <h4>💭 How I'm Feeling</h4>
                    <p>${entry.feelings}</p>
                </div>
                ` : ''}
                
                ${entry.what_came_up ? `
                <div class="entry-field">
                    <h4>🌊 What Came Up</h4>
                    <p>${entry.what_came_up}</p>
                </div>
                ` : ''}
                
                ${entry.emotions_released ? `
                <div class="entry-field">
                    <h4>🕊️ Emotions Released</h4>
                    <p>${entry.emotions_released}</p>
                </div>
                ` : ''}
                
                ${entry.next_steps ? `
                <div class="entry-field">
                    <h4>🌱 Next Steps</h4>
                    <p>${entry.next_steps}</p>
                </div>
                ` : ''}
            </div>
        </div>
    `).join('');
}

function getFormData() {
    const form = document.getElementById('journal-form');
    const formData = new FormData(form);
    
    return {
        affirmation: formData.get('affirmation'),
        general_reflection: formData.get('general_reflection'),
        feelings: formData.get('feelings'),
        what_came_up: formData.get('what_came_up'),
        emotions_released: formData.get('emotions_released'),
        next_steps: formData.get('next_steps'),
        emotion_selected: formData.get('emotion_selected'),
        frequency_tag: formData.get('frequency_tag'),
        vibration_word: formData.get('vibration_word'),
        prompt_used: formData.get('prompt_used')
    };
}

function clearForm() {
    const form = document.getElementById('journal-form');
    form.reset();
    skipPrompt();
    
    document.getElementById('affirmation-select').value = '';
    document.getElementById('selected-affirmation').style.display = 'none';
    document.getElementById('selected-affirmation').textContent = '';
    
    clearEmotionSelection();
}

async function saveToSacredSpace() {
    // In quiet mode, check authentication before saving
    if (isQuietMode() && !currentUser) {
        if (confirm('To save your journal entry, you need to create a free account. Would you like to sign up now?')) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname + window.location.search);
        }
        return;
    }
    
    const data = getFormData();
    
    try {
        const response = await fetch(`${API_BASE}/entries`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        });
        
        if (response.status === 401) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
            return;
        }
        
        if (response.ok) {
            clearForm();
            showNotification('Journal entry saved to your Sacred Space. View it in your Profile.');
        } else {
            showNotification('Error saving entry. Please try again.', 'error');
        }
    } catch (error) {
        console.error('Error saving entry:', error);
        showNotification('Error saving entry. Please try again.', 'error');
    }
}

async function saveAndUploadToDrive() {
    // In quiet mode, check authentication before saving
    if (isQuietMode() && !currentUser) {
        if (confirm('To save your journal entry, you need to create a free account. Would you like to sign up now?')) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname + window.location.search);
        }
        return;
    }
    
    const data = getFormData();
    
    try {
        showNotification('Saving and uploading to Google Drive...', 'info');
        
        const response = await fetch(`${API_BASE}/entries`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        });
        
        if (response.status === 401) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
            return;
        }
        
        if (response.ok) {
            const entry = await response.json();
            
            // Now upload to drive
            const driveResponse = await fetch(`${API_BASE}/entries/${entry.id}/upload-to-drive`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                }
            });
            
            const driveResult = await driveResponse.json();
            
            clearForm();
            
            if (driveResponse.ok && driveResult.success) {
                showNotification('Entry saved and uploaded to Google Drive!');
            } else {
                showNotification('Entry saved but could not upload to Drive: ' + (driveResult.error || 'Unknown error'), 'error');
            }
        } else {
            showNotification('Error saving entry. Please try again.', 'error');
        }
    } catch (error) {
        console.error('Error saving entry:', error);
        showNotification('Error saving entry. Please try again.', 'error');
    }
}

async function saveAndDownload() {
    // In quiet mode, check authentication before saving
    if (isQuietMode() && !currentUser) {
        if (confirm('To save your journal entry, you need to create a free account. Would you like to sign up now?')) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname + window.location.search);
        }
        return;
    }
    
    const data = getFormData();
    
    try {
        const response = await fetch(`${API_BASE}/entries`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        });
        
        if (response.status === 401) {
            window.location.href = '/login.html?next=' + encodeURIComponent(window.location.pathname);
            return;
        }
        
        if (response.ok) {
            const entry = await response.json();
            
            clearForm();
            
            // Download PDF
            window.open(`${API_BASE}/entries/${entry.id}/pdf`, '_blank');
            showNotification('Entry saved and PDF is downloading...');
        } else {
            showNotification('Error saving entry. Please try again.', 'error');
        }
    } catch (error) {
        console.error('Error saving entry:', error);
        showNotification('Error saving entry. Please try again.', 'error');
    }
}

async function deleteEntry(id) {
    if (!confirm('Are you sure you want to delete this journal entry?')) {
        return;
    }
    
    try {
        const response = await fetch(`${API_BASE}/entries/${id}`, {
            method: 'DELETE'
        });
        
        if (response.ok) {
            await loadEntries();
            showNotification('Entry deleted successfully');
        } else {
            showNotification('Error deleting entry', 'error');
        }
    } catch (error) {
        console.error('Error deleting entry:', error);
        showNotification('Error deleting entry', 'error');
    }
}

async function downloadPDF(id) {
    try {
        window.open(`${API_BASE}/entries/${id}/pdf`, '_blank');
        showNotification('📥 PDF is being downloaded...');
    } catch (error) {
        console.error('Error downloading PDF:', error);
        showNotification('Error downloading PDF', 'error');
    }
}

async function uploadToDrive(id) {
    try {
        showNotification('☁️ Uploading to Google Drive...', 'info');
        
        const response = await fetch(`${API_BASE}/entries/${id}/upload-to-drive`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        });
        
        const result = await response.json();
        
        if (response.ok && result.success) {
            showNotification(`✅ ${result.message}`);
        } else {
            showNotification(result.error || 'Error uploading to Google Drive', 'error');
        }
    } catch (error) {
        console.error('Error uploading to Drive:', error);
        showNotification('Error uploading to Google Drive', 'error');
    }
}

function showNotification(message, type = 'success') {
    const notification = document.createElement('div');
    notification.className = `notification ${type}`;
    notification.textContent = message;
    
    const bgColors = {
        'success': '#C8963E',
        'error': '#e74c3c',
        'info': '#3498db'
    };
    
    notification.style.cssText = `
        position: fixed;
        top: 20px;
        right: 20px;
        background: ${bgColors[type] || bgColors.success};
        color: white;
        padding: 1rem 1.5rem;
        border-radius: 8px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.2);
        z-index: 10000;
        animation: slideIn 0.3s ease;
    `;
    
    document.body.appendChild(notification);
    
    setTimeout(() => {
        notification.style.animation = 'slideOut 0.3s ease';
        setTimeout(() => notification.remove(), 300);
    }, 3000);
}

// Video Modal Functions
function openVideoModal() {
    const modal = document.getElementById('video-modal');
    const video = document.getElementById('welcome-video');
    
    modal.style.display = 'flex';
    video.currentTime = 0; // Reset video to start
    video.play();
}

function closeVideoModal() {
    const modal = document.getElementById('video-modal');
    const video = document.getElementById('welcome-video');
    
    modal.style.display = 'none';
    video.pause();
    video.currentTime = 0; // Reset video when closed
}

document.addEventListener('DOMContentLoaded', async () => {
    const isAuthenticated = await checkAuthentication();
    
    // Always populate prompts (works for both logged in and quiet mode)
    populatePromptDropdown();
    
    
    // Video modal event listeners
    const videoBtn = document.getElementById('welcome-video-btn');
    const closeBtn = document.querySelector('.video-close-btn');
    const modal = document.getElementById('video-modal');
    
    if (videoBtn) {
        videoBtn.addEventListener('click', openVideoModal);
    }
    
    if (closeBtn) {
        closeBtn.addEventListener('click', closeVideoModal);
    }
    
    // Close modal when clicking outside the video content
    if (modal) {
        modal.addEventListener('click', (e) => {
            if (e.target === modal) {
                closeVideoModal();
            }
        });
    }
    
    // Close modal with Escape key
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            const modal = document.getElementById('video-modal');
            if (modal && modal.style.display === 'flex') {
                closeVideoModal();
            }
        }
    });
    
    const style = document.createElement('style');
    style.textContent = `
        @keyframes slideIn {
            from { transform: translateX(400px); opacity: 0; }
            to { transform: translateX(0); opacity: 1; }
        }
        @keyframes slideOut {
            from { transform: translateX(0); opacity: 1; }
            to { transform: translateX(400px); opacity: 0; }
        }
    `;
    document.head.appendChild(style);
});
